#!/usr/bin/env bash
# HOOK: sensei-2week-report
# EVENT: systemd-timer (one-shot 2026-05-16)
# MATCHER: n/a
# PURPOSE: Capture smart-context + context-audit telemetry into dated Obsidian note
# EXIT: 0=ok (always; failures noted in report)

set -u  # not -e — partial output beats nothing

REPORT_DIR="$HOME/Documents/Obsidian Vault/Sensei"
REPORT="$REPORT_DIR/weekly-2026-05-16.md"
LOG="$HOME/.claude/hooks/smart-context.log"
mkdir -p "$REPORT_DIR"

DATE_NOW="$(date '+%Y-%m-%d %H:%M %Z')"

# Count smart-context invocations to gate prune recommendation
INVOC=0
if [ -f "$LOG" ]; then
  INVOC=$(wc -l < "$LOG" 2>/dev/null || echo 0)
fi

{
  echo ""
  echo "## Sensei 2-week telemetry report — $DATE_NOW"
  echo ""
  echo "_Auto-generated by systemd timer \`sensei-context-audit.timer\`._"
  echo ""

  echo "### Smart-context telemetry"
  echo ""
  echo '```'
  if python3 "$HOME/.claude/hooks/smart-context-stats.py" 2>&1; then
    :
  else
    echo "[error: stats CLI failed exit $?]"
  fi
  echo '```'
  echo ""

  echo "### Context budget"
  echo ""
  echo '```'
  if python3 "$HOME/.claude/hooks/context-audit.py" --orphans 2>&1; then
    :
  else
    echo "[error: context-audit failed exit $?]"
  fi
  echo '```'
  echo ""

  echo "### Memory archival candidates (Phase 4)"
  echo ""
  echo '```'
  if python3 "$HOME/.claude/hooks/memory-archive-candidates.py" 2>&1; then
    :
  else
    echo "[error: archive-candidates failed exit $?]"
  fi
  echo '```'
  echo ""

  echo "### Orphan prune candidates"
  echo ""
  if [ "$INVOC" -lt 20 ]; then
    echo "_Only $INVOC smart-context invocations logged. Need ≥20 before prune is reliable. Skipping recommendations._"
  else
    echo "_Telemetry sufficient ($INVOC invocations). Orphan list above are candidates for archive to \`~/.claude/memory/_archive/\`._"
    echo ""
    echo "**Recommended action:** review the orphan list manually, then for each genuinely stale entry:"
    echo ""
    echo '```bash'
    echo 'mkdir -p ~/.claude/memory/_archive'
    echo 'mv ~/.claude/memory/<orphan_file>.md ~/.claude/memory/_archive/'
    echo '# then prune corresponding line from ~/.claude/memory/INDEX.md'
    echo '```'
    echo ""
    echo "**Do NOT auto-archive** — orphan ≠ useless. Some are infrequently relevant but high-value when they hit."
  fi
  echo ""
  echo "---"
} >> "$REPORT"

echo "Wrote report → $REPORT"
exit 0
